name: Build
on:
  push:
    branches:
      - master  

jobs:
  release:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true

      - name: Prepare Files
        run: |
          git rev-parse HEAD > firmware.version
          mv Santroller/ardwiino_script_post_tool.py Santroller/ardwiino_script_post.py
          rm -rf Santroller/.git*
          rm -rf Santroller/*.md
          rm Santroller/LICENSE
          rm Santroller/.gitignore
          rm -rf Santroller/.github

      - name: Create Zip File
        run: |
          cd Santroller
          zip -r ../firmware.zip *
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: firmware.zip
